### ISSUE TITLE
enable_autocompletion unexpected

### ISSUE THREAD

**Issue by dpwrussell** [druths/arghandler#12]
``` python
#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

from arghandler import ArgumentHandler

if __name__ == '__main__':
    handler = ArgumentHandler(enable_autocompletion=True)
    handler.run()
```

Result:

```
Traceback (most recent call last):
  File "./manager.py", line 7, in <module>
    handler = ArgumentHandler(enable_autocompletion=True)
  File "/Users/dpwrussell/.virtualenvs/omero/lib/python2.7/site-packages/arghandler/base.py", line 88, in __init__
    argparse.ArgumentParser.__init__(self,*args,**kwargs)
TypeError: __init__() got an unexpected keyword argument 'enable_autocompletion'
```

``` sh
$ pip list | grep arghandler
arghandler (1.1.0)
```

**Comment by druths** [comment]
Same version problem here.  Updating through pypi should fix this.
