### ISSUE TITLE
1.3.0 release not pip-installable in Python 2.7.18

### ISSUE THREAD

**Issue by tylercrumpton** [druths/arghandler#23]
Hello! It seems that it's not currently possible to pip-install arghandler==1.3.0 in Python 2.7.18 due to an error in setup.py:

```
Collecting arghandler
  Downloading arghandler-1.3.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: {snipped-dir}/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'{snipped-dir}/arghandler/setup.py'"'"'; __file__='"'"'{snipped-dir}/arghandler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base {snipped-dir}
         cwd: {snipped-dir}/arghandler/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "{snipped-dir}/arghandler/setup.py", line 6, in <module>
        with open("README.md", "r", encoding="utf-8") as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

arghandler==1.2.0 installs correctly with no error.

**Comment by druths** [comment]
Oops!  Thanks for pointing this out!  Just made the fix in main.  Pushing the fix to pip now (as 1.3.1).

**Comment by tylercrumpton** [comment]
Amazing, thank you so much for the quick fix! I’ll give it a shot shortly!

**Comment by tylercrumpton** [comment]
Looks good here! Thanks so much!
